### ISSUE TITLE
Minificar Css y Html

### ISSUE THREAD

**Issue by alu0100812534** [ULL-ESIT-GRADOII-PL/mocha-y-chai-edu-daniel#8]
Creo que deberias minificar algunos ficheros mas del directorio vendor, como mocha.js por ejemplo #5

**Comment by alu0100825985** [comment]
Ya estaba solucionado en el directorio de trabajo, faltó hacer un pull request con el cambio añadido a este repositorio. Ya mismo lo corrijo, gracias por la aclaración.
